version: '3.1'
services:
  python:
    container_name: python
    build:
      context: .
      dockerfile: flask.Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:16.2-alpine3.19
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    restart: always

volumes:
  db_data: {}